name: Build Flatpak

on:
  # Enable manual run
  workflow_dispatch:

jobs:
  build-flutter-app:
    name: Build and compressed Flutter app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.8.0

      - name: Build Flutter linux version
        run: |
          flutter config --enable-linux-desktop
          flutter pub get
          flutter build linux

      - name: Compress Flutter build
        run: tar -C build/linux/x64/release/bundle -cvf FlutterApp-Linux-Portable.tar.gz .

      - name: Upload app archive for next steps
        uses: actions/upload-artifact@v2
        with:
          name: FlutterApp-Archive
          path: FlutterApp-Linux-Portable.tar.gz

  build-flatpak:
    name: Build flatpak
    needs: build-flutter-app
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-21.08
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download app archive
        uses: actions/download-artifact@v3
        with:
          name: FlutterApp-Archive

      - name: Build .flatpak
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: FlutterApp.flatpak
          manifest-path: com.example.FlutterApp.json

      - name: Upload .flatpak artifact to workflow
        uses: actions/upload-artifact@v2
        with:
          name: Flatpak artifact
          path: FlutterApp.flatpak
